if(EXISTS "/home/ubuntu/conann-dev/faiss-1.9.0/tests/faiss_test[1]_tests.cmake")
  include("/home/ubuntu/conann-dev/faiss-1.9.0/tests/faiss_test[1]_tests.cmake")
else()
  add_test(faiss_test_NOT_BUILT faiss_test_NOT_BUILT)
endif()
